export const cardArray = [
    {
        id: 0,
        title: 'Первый автомобиль',
        price: '5000 $',
        address: 'Казань, р-н Авиастроительный',
        date: '28 сентября 15:37',
        img: '/pictures/card-image.png',
    },
    {
        id: 1,
        title: 'Второй автомобиль',
        price: '5001 $',
        address: 'Казань, р-н Авиастроительный',
        date: '28 сентября 15:37',
        img: '/pictures/card-image.png',
    },
       {
        id: 2,
        title: 'Третий автомобиль',
        price: '5002 $',
        address: 'Казань, р-н Авиастроительный',
        date: '28 сентября 15:37',
        img: '/pictures/card-image.png',
    },
       {
        id: 3,
        title: 'Четвёртый автомобиль',
        price: '5003 $',
        address: 'Казань, р-н Авиастроительный',
        date: '28 сентября 15:37',
        img: '/pictures/card-image.png',
    },
       {
        id: 4,
        title: 'Пятый автомобиль',
        price: '5004 $',
        address: 'Казань, р-н Авиастроительный',
        date: '28 сентября 15:37',
        img: '/pictures/card-image.png',
    },
       {
        id: 5,
        title: 'Шестой автомобиль',
        price: '5005 $',
        address: 'Казань, р-н Авиастроительный',
        date: '28 сентября 15:37',
        img: '/pictures/card-image.png',
    },
]